import * as fs from "fs";
import * as path from "path";

/**
 * Generates: data/novenasManifest.ts
 *
 * Manifest maps:
 *   id -> require("./novenas/<id>.json")
 *
 * This must be static require calls (Metro bundler needs them).
 */

function main() {
  const root = process.cwd();
  const novenasDir = path.join(root, "data", "novenas");
  const outPath = path.join(root, "data", "novenasManifest.ts");

  if (!fs.existsSync(novenasDir)) {
    console.log(`Directory not found (creating): ${novenasDir}`);
    fs.mkdirSync(novenasDir, { recursive: true });
  }

  const files = fs
    .readdirSync(novenasDir)
    .filter((f) => f.toLowerCase().endsWith(".json"))
    .sort((a, b) => a.localeCompare(b));

  const entries = files.map((f) => {
    const id = f.replace(/\.json$/i, "");
    // Path is relative to data/novenasManifest.ts
    return { id, requirePath: `./novenas/${f}` };
  });

  const lines: string[] = [];
  lines.push("/* AUTO-GENERATED FILE. DO NOT EDIT BY HAND. */");
  lines.push("/* Generated by: scripts/build-novenas-manifest.ts */");
  lines.push("");
  lines.push("export const NOVENA_MANIFEST: Record<string, any> = {");

  for (const e of entries) {
    lines.push(`  "${e.id}": require("${e.requirePath}"),`);
  }

  lines.push("};");
  lines.push("");
  lines.push("export function getNovenaContent(id: string): any | null {");
  lines.push("  return NOVENA_MANIFEST[id] ?? null;");
  lines.push("}");
  lines.push("");

  const contents = lines.join("\n");
  safeAtomicWrite(outPath, contents);

  console.log(`Wrote manifest: ${outPath}`);
  console.log(`Entries: ${entries.length}`);
}

function safeAtomicWrite(outPath: string, contents: string) {
  const tmpPath = outPath + ".tmp";
  fs.writeFileSync(tmpPath, contents, "utf8");
  fs.renameSync(tmpPath, outPath);
}

main();
